//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedRoom
    {
        public long BookingID { get; set; }
        public int RoomID { get; set; }
        public Nullable<int> AdultsNo { get; set; }
        public Nullable<int> ChildNo { get; set; }
        public string GuestName { get; set; }
        public string GuestPhone { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Room Room { get; set; }
    }
}
