//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookedRooms = new HashSet<BookedRoom>();
            this.BookedServices = new HashSet<BookedService>();
            this.Payments = new HashSet<Payment>();
        }
    
        public long BookingID { get; set; }
        public int BookingStatusID { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
        public int Nights { get; set; }
        public string HasCar { get; set; }
        public System.DateTime BookDate { get; set; }
        public string Notes { get; set; }
        public string CreditCardName { get; set; }
        public string CreditCardNo { get; set; }
        public Nullable<int> CreditCardSecurityCode { get; set; }
        public string CreditCardExpiry { get; set; }
        public string ReferenceNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public Nullable<decimal> RestSum { get; set; }
        public int ReferredByID { get; set; }
        public Nullable<int> GuestID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookedRoom> BookedRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookedService> BookedServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual BookingStatu BookingStatu { get; set; }
        public virtual ReferredBy ReferredBy { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
