//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTypesView
    {
        public string RoomTypeDesc { get; set; }
        public decimal RoomPrice { get; set; }
        public int NumberOfAdults { get; set; }
        public int NumberOfBeds { get; set; }
        public Nullable<int> NumberOfChildren { get; set; }
        public string BedType { get; set; }
        public string SmokingAllowed { get; set; }
        public string RoomAddDescription { get; set; }
    }
}
