//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodayCheckIn
    {
        public string BookingStatusName { get; set; }
        public string GuestName { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
        public int Nights { get; set; }
        public string HasCar { get; set; }
        public System.DateTime BookDate { get; set; }
        public string Notes { get; set; }
        public string CreditCardName { get; set; }
        public string CreditCardNo { get; set; }
        public Nullable<int> CreditCardSecurityCode { get; set; }
        public string CreditCardExpiry { get; set; }
        public string ReferenceNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public Nullable<decimal> RestSum { get; set; }
    }
}
